name: flutter_paypal_payment
description: This package simplifies integrating PayPal payments into your mobile app. Key features include seamless in-app PayPal integration
version: 2.0.0
homepage: https://github.com/MazenxELGayar/flutter_paypal_payment_checkout_v2

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null

